name: flutter_meta_appads_sdk
description: "This Flutter plugin provides a simple interface to interact with the Meta SDK. It allows you to initialize the SDK, set user data (Advanced Attribution), and log events/purchases."
version: 1.0.1
homepage: https://github.com/sdurban/flutter_meta_appads_sdk
repository: https://github.com/sdurban/flutter_meta_appads_sdk

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cat.durban.sergio.flutter_meta_appads_sdk
        pluginClass: FlutterMetaAppadsSdkPlugin
      ios:
        pluginClass: FlutterMetaAppadsSdkPlugin